// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c8e9ab25-8e36-440e-a1fa-4c2cbbcfd450";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onColor1Change();
void onColor2Change();

int color1;
int color2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(color1, READWRITE, ON_CHANGE, onColor1Change);
  ArduinoCloud.addProperty(color2, READWRITE, ON_CHANGE, onColor2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
